filetype plugin on
syntax on
set ai
set laststatus=2
" true colours
set background=dark
"set colorscheme
colorscheme habamax
"Global settings
set nu rnu " relative line numbering
set clipboard=unnamed " public copy/paste register
set ruler
set showcmd
set noswapfile " doesn't create swap files
set noshowmode
set shortmess+=c
set omnifunc=syntaxcomplete#Complete
set backspace=indent,eol,start " let backspace delete over lines
set autoindent " enable auto indentation of lines
set smartindent " allow vim to best-effort guess the indentation
set pastetoggle=<F2> " enable paste mode
set wildmenu "graphical auto complete menu
set lazyredraw "redraws the screne when it needs to
set showmatch "highlights matching brackets
set incsearch "search as characters are entered
set hlsearch "highlights matching searches
set nocompatible                            " be iMproved
set nowrap                                  " no text wrap
set showcmd                                 " show command in status line
set showmatch                               " show matching brackets
set showmode                                " show current mode
set ruler                                   " show the line and column numbers of the cursor
"set list                                    " show problematic characters
set number                                  " show the line number
set lazyredraw                              " don't redraw the screen all the time

highlight Comment ctermfg=green

"clears highlights
nnoremap // :noh<return>
" moves current line down or up
nnoremap <leader>_ ddkP
" open vimrc in vertical split
nnoremap <leader>- ddp
" update changes into current buffer
nnoremap <leader>h  :split  $MYVIMRC<cr>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
" enable or disable line wrapping in current buffer
nnoremap <buffer> <localleader>w :set wrap!<cr>

" c++11 support in syntastic
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11'

"assembler  syntax
autocmd BufNewFile,BufRead *.asm set syntax=nasm


" run code
augroup compileandrun
    autocmd!
    autocmd filetype python nnoremap <f5> :w <bar> :!python3 % <cr>
    autocmd filetype cpp nnoremap <f5> :w <bar> !g++ -std=c++11 % <cr> :vnew <bar> :te "a.exe" <cr><cr>
    autocmd filetype cpp nnoremap <f6> :vnew <bar> :te "a.exe" <cr>
    autocmd filetype c nnoremap <f5> :w <bar> !make %:r && ./%:r <cr>
    autocmd filetype java nnoremap <f5> :w <bar> !javac % && java %:r <cr>
augroup END

